
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
//import { useContext } from 'react'

//import Header from './_components/ui_parts/header'
//import Footer from './_components/ui_parts/footer'
//import { UserStateContext } from '@/app/_common/hooks/statemanagement';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}

/*
<Header {...userstate_.loginstate}/>
        {children}
        <Footer/> */
